<a href="https://colab.research.google.com/github/abisolaabimbola69/myproject/blob/main/Working_with_large_dataset_using_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
A <- matrix(c(20,5,40,6),ncol=2)
print(A)
C <-t(A)
Ainverse <- solve(A)
print(Ainverse)

     [,1] [,2]
[1,]   20   40
[2,]    5    6
        [,1]  [,2]
[1,] -0.0750  0.50
[2,]  0.0625 -0.25


In [ ]:
B <- eigen(A)
print(B$value)

[1] 28.779734 -2.779734


In [ ]:
print(B$vector)

          [,1]       [,2]
[1,] 0.9767482 -0.8689666
[2,] 0.2143897  0.4948707


In [ ]:
A<- matrix(c(5,6,7,8,9,10,2,0,5),ncol=3)
print(A)
B <- eigen(A)
print(B$vector)
Ainverse <- solve(A)
print(Ainverse)

     [,1] [,2] [,3]
[1,]    5    8    2
[2,]    6    9    0
[3,]    7   10    5
           [,1]       [,2]        [,3]
[1,] -0.4849827  0.2284166 -0.83812358
[2,] -0.4482837 -0.2666343  0.53776465
[3,] -0.7508885  0.9363397  0.09142233
           [,1]       [,2]       [,3]
[1,] -2.1428571  0.9523810  0.8571429
[2,]  1.4285714 -0.5238095 -0.5714286
[3,]  0.1428571 -0.2857143  0.1428571


To transpose

In [ ]:
C <-t(A)
print(C)

     [,1] [,2] [,3]
[1,]    5    6    7
[2,]    8    9   10
[3,]    2    0    5


TO call a table

In [ ]:
read.table("")