<a href="https://colab.research.google.com/github/abisolaabimbola69/myproject/blob/main/Working_with_matrices_in_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
A = matrix(c(20,5,40,6),ncol=2)
B = matrix(c(7,9,8,10),ncol=2)
C = A - B
print(C)

     [,1] [,2]
[1,]   13   32
[2,]   -4   -4


In [ ]:
D <- A+B
print(D)

     [,1] [,2] [,3]
[1,]    7    9    9
[2,]    7   11    2
[3,]    7   11    8


In [ ]:
E <- A%*%B
print(E)

     [,1] [,2] [,3]
[1,]   18   23   57
[2,]   21   24   60
[3,]   24   32   84


In [ ]:
A <- matrix(c(5,6,7,8,9,10,2,0,5),ncol=3)
B <- matrix(c(2,1,0,1,2,1,7,2,3),ncol=3)
C <- matrix(1:9,ncol=3)
E <- A - B - C
print(E)


     [,1] [,2] [,3]
[1,]    2    3  -12
[2,]    3    2  -10
[3,]    4    3   -7


In [ ]:
G <- A%*%B
print(G)

     [,1] [,2]
[1,]  460  580
[2,]   83  105


In [ ]:
A <- matrix(c(20,5,40,6),ncol=2)
PP <-det(A)
print(PP)

[1] -80


In [ ]:
B = matrix(c(7,8,9,10),ncol=2)
PP <- det(B)
print(PP)

[1] -2


Assignment

1.   Do a 5 for A-D matrix where A = 1-25
addition, subtraction, multiplication, division, det A-D
2.   List item

